include:
  - board: seeeduino_xiao_ble
    shield: forager_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: forager_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: seeeduino-xiao-ble-settings-reset
  - board: seeeduino_xiao_ble
    shield: forager_dongle prospector_adapter
    artifact-name: forager-dongle
